server:
  port: 8088
  servlet:
    encoding:
      force-response: true


spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: localhost:3306/
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

jwt:
  secret: secretKey